name: 'VPNConnect'
description: 'Connects to VPN using openvpn'
author: 'Prayatna Koirala'
inputs:
  VPN_USER:
    description: 'Your openvpn username'
    required: true
    default: ''
  VPN_PASS:
    description: 'Your openvpn password'
    required: true
    default: ''
  VPN_CONFIG:
    description: 'Your openvpn configuration file'
    required: true
    default: ''
runs:
  using: 'composite'
  steps:
    - run: |
        sudo apt-get install openvpn -y
      shell: bash
    - run: |
        echo -e "${{ inputs.VPN_USER }}\n${{ inputs.VPN_PASS }}" > ~/.vpncreds
        sudo openvpn --config ${{ inputs.VPN_CONFIG }} --auth-user-pass ~/.vpncreds
        sleep 10s
      shell: bash
