name: 'Sqlcmd'
description: 'Executes query files with sqlcmd '
author: 'Laudio'
inputs:
  query_file:
    description: 'The query file to be executed'
    required: false
    default: 'query.sql'
  db_host:
    description: 'Your database host'
    required: true
  db_password:
    description: 'Your db password'
    required: true
  db_port:
    description: 'Database port'
    required: false
    default: 1337
runs:
  using: 'composite'
  steps:
    - run: |
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
        sudo apt-get update 
        sudo apt-get install mssql-tools unixodbc-dev
        export PATH=$PATH:/opt/mssql-tools/bin
      shell: bash
    - run: |
        sqlcmd -?
      shell: bash
