name: 'Sqlcmd'
description: 'Executes query files with sqlcmd '
author: 'Laudio'
inputs:
  query_file:
    description: 'The query file to be executed'
    required: false
    default: 'query.sql'
  db_host:
    description: 'Your database host'
    required: true
  db_password:
    description: 'Your db password'
    required: true
  db_port:
    description: 'Database port'
    required: false
    default: 1337
runs:
  using: 'composite'
  steps:
    - run: |
        apk update
        apk add gcc libc-dev g++ libffi-dev libxml2 unixodbc-dev unixodbc mariadb-dev libstdc++6
        apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib curl gnupg

        curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/msodbcsql17_17.8.1.1-1_amd64.apk
        curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/mssql-tools_17.8.1.1-1_amd64.apk

        curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/msodbcsql17_17.8.1.1-1_amd64.sig
        curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/mssql-tools_17.8.1.1-1_amd64.sig

        curl https://packages.microsoft.com/keys/microsoft.asc  | gpg --import -
        gpg --verify msodbcsql17_17.8.1.1-1_amd64.sig msodbcsql17_17.8.1.1-1_amd64.apk
        gpg --verify mssql-tools_17.8.1.1-1_amd64.sig mssql-tools_17.8.1.1-1_amd64.apk

        apk add --allow-untrusted msodbcsql17_17.8.1.1-1_amd64.apk
        apk add --allow-untrusted mssql-tools_17.8.1.1-1_amd64.apk
        export PATH=$PATH:/opt/mssql-tools/bin
      shell: bash
    - run: |
        sqlcmd -?
      shell: bash
