name: 'SonarScan'
description: 'Runs sonar-scanner command with the sonar scanner cli 4.6.2. '
author: 'Laudio'
inputs:
  source_directory:
    description: 'The source directory to be scanned'
    required: false
    default: '.'
  sonar_host_url:
    description: 'Your sonarqube server host URL'
    required: true
  sonar_token:
    description: 'Your Sonar Token'
    required: true
  service_name:
    description: 'An additional service name if its a monorepo'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - run: |
        sudo wget  https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        sudo apt-get install unzip -y
        sudo unzip sonar-scanner-cli-4.6.2.2472-linux.zip 
        sudo mv sonar-scanner-4.6.2.2472-linux/ /sonar-scanner
        sudo rm sonar-scanner-cli-4.6.2.2472-linux.zip 
        sudo chmod +x /sonar-scanner/bin/sonar-scanner
      shell: bash
    - run: |
        GIT_BRANCH_FORMATTED=$(echo "${GITHUB_REF#refs/heads/}" | sed -r 's/[/]+/-/g')
        SERVICE_NAME=${{ inputs.service_name }}
        GIT_SERVICE_NAME=$(echo "${SERVICE_NAME:+_$SERVICE_NAME}")
        /sonar-scanner/bin/sonar-scanner \
        -Dsonar.projectKey=$(echo "${GITHUB_REPOSITORY#*/}${GIT_SERVICE_NAME}_${GIT_BRANCH_FORMATTED}") \
        -Dsonar.sources=${{ inputs.source_dir }} \
        -Dsonar.host.url=${{ inputs.sonar_host_url }} \
        -Dsonar.login=${{ inputs.sonar_token }}
      shell: bash
